name: Build_25_03_28
options:
  bundleIdPrefix: com.cheemcloud
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.29.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 7.1.0
targets:
  Build_25_03_28:
    type: application
    platform: iOS
    sources:
      - path: Sources/Build_25_03_28App.swift
      - path: Sources/Build_25_03_28
    resources:
      - path: Sources/Build_25_03_28/Resources/GoogleService-Info.plist
      - path: Sources/Build_25_03_28/Resources/Info.plist
    settings:
      base:
        INFOPLIST_FILE: Sources/Build_25_03_28/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.cheemcloud.build2503
        DEVELOPMENT_TEAM: 2K4J2K4J2K
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: false
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: Firebase
        products:
          - FirebaseCore
          - FirebaseAuth
          - FirebaseFirestore
          - FirebaseStorage
      - package: GoogleSignIn
        products:
          - GoogleSignIn
          - GoogleSignInSwift 