name: Build_25_03_28
options:
  bundleIdPrefix: com.cheemhang
  deploymentTarget:
    iOS: 15.0
packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.0.0
targets:
  Build_25_03_28:
    type: application
    platform: iOS
    sources:
      - path: Sources/Build_25_03_28
    settings:
      base:
        INFOPLIST_FILE: Sources/Build_25_03_28/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.cheemhang.Build_25_03_28
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
    dependencies:
      - package: FirebaseSDK
        product: Firebase
      - package: GoogleSignIn
        product: GoogleSignIn 